### ISSUE TITLE
不知道怎么配置，无法使用

### ISSUE THREAD

**Issue by zhishixiang** [onebot-walle/nonebot_adapter_walleq#2]
10-11 13:41:45 [ERROR] nonebot.plugin.manager | Failed to import "nonebot_plugin_localstore"
Traceback (most recent call last):
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\bot.py", line 3, in <module>
    from nonebot_adapter_walleq import Adapter as WalleQAdapter
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot_adapter_walleq\__init__.py", line 16, in <module>
    require("nonebot_plugin_localstore")
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot\plugin\load.py", line 179, in require
    plugin = load_plugin(name)
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\root\miniconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot_plugin_localstore\__init__.py", line 30, in <module>
    plugin_config = Config.parse_obj(get_driver().config)
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Traceback (most recent call last):
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\bot.py", line 3, in <module>
    from nonebot_adapter_walleq import Adapter as WalleQAdapter
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot_adapter_walleq\__init__.py", line 16, in <module>
    require("nonebot_plugin_localstore")
  File "C:\Users\root\▒▒Ŀ\nonebot_plugin_msg2pdf\.venv\Lib\site-packages\nonebot\plugin\load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_localstore"!

用默认导入适配器的方式就会报错，也没有看到有wiki

**Comment by abrahum** [comment]
walle-q has been archived.This adapter is not working any more.
