### ISSUE TITLE
RuntimeError: Cannot load plugin "nonebot_plugin_localstore"!

### ISSUE THREAD

**Issue by neohary** [onebot-walle/nonebot_adapter_walleq#3]
在env.prod配置了
```
DRIVER=~fastapi
walle_q={"xxxx":{"protocol":2,"password":null}}
walle_q_leveldb=false
walle_q_sled=false
```
也确认已经安装了nonebot_plugin_localstore插件，运行nb run会产生以下错误
```
使用 Python: D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Scripts\python.exe
11-08 17:57:42 [ERROR] nonebot.plugin.manager | Failed to import "nonebot_plugin_localstore"
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot_adapter_walleq\__init__.py", line 16, in <module>
    require("nonebot_plugin_localstore")
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot\plugin\load.py", line 179, in require
    plugin = load_plugin(name)
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot_plugin_localstore\__init__.py", line 30, in <module>
    plugin_config = Config.parse_obj(get_driver().config)
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot_adapter_walleq\__init__.py", line 16, in <module>
    require("nonebot_plugin_localstore")
  File "D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Lib\site-packages\nonebot\plugin\load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_localstore"!
```

**Comment by neohary** [comment]
去掉这个adapter，执行nb localstore是正常的
```
PS D:\work\Bot_Project\nonebot-chatgpt\nonebot-main> nb localstore
使用 Python: D:\work\Bot_Project\nonebot-chatgpt\nonebot-main\.venv\Scripts\python.exe
11-08 18:03:16 [SUCCESS] nonebot | NoneBot is initializing...
11-08 18:03:16 [INFO] nonebot | Current Env: prod
11-08 18:03:16 [SUCCESS] nonebot | Succeeded to load plugin "echo" from "nonebot.plugins.echo"
11-08 18:03:16 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_localstore"
Cache Dir:  C:\Users\Administrator\AppData\Local\nonebot2\Cache
Config Dir:  C:\Users\Administrator\AppData\Roaming\nonebot2
Data Dir:  C:\Users\Administrator\AppData\Local\nonebot2
```

**Comment by tllvmys** [comment]
大佬解决这个问题了吗？我也遇到了

**Comment by abrahum** [comment]
walle-q has been archived.This adapter is not working any more.
